pipeline {
    agent any 
    stages {
        stage('SCM') {
            steps {
                 git credentialsId: 'GitHub_Credentials', url: 'https://github.com/vpolice3/accouting-service.git'
            }
        }
        stage('Build'){
            steps{
                sh '''
                cd Accounting-Service
                mvn clean install -DskipTests=true'
                '''
            }
        }
    }
}
