pipeline {
    agent any 
    stages {
        stage('SCM') {
            steps {
                 git credentialsId: 'GitHub_Credentials', url: 'https://github.com/vpolice3/accouting-service.git'
            }
        }
        stage('Build'){
            steps{
                sh '''
                def mvnHome = tool name: 'MAVEN_HOME', type: 'maven'
                def mvnCMD = "${mvnHome}/bin/mvn"
                cd Accounting-Service
                "${mvnCMD} clean install -DskipTests=true"
                '''
            }
        }
    }
}
